/*
    일대 다 관계의 테이블 생성
    
    1. 명칭 
        1) 부모 테이블 : 일(1), PK를 가진 테이블
        2) 자식 테이블 : 다(M), FK를 가진 테이블
    2. 생성
        부모 테이블을 먼저 생성하고, 자식 테이블을 나중에 생성
    3. 삭제
        자식 테이블을 먼저 삭제하고, 부모 테이블을 나중에 삭제
*/
-- 학교 테이블
-- 부모 테이블 : PK를 가진 테이블
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL (
    SCH_CODE NUMBER(1) NOT NULL PRIMARY KEY,
    SCH_NAME VARCHAR2(20 BYTE) NOT NULL   
);

DROP TABLE SCHOOL;
CREATE TABLE SCHOOL (
    SCH_CODE NUMBER(1) NOT NULL,
    SCH_NAME VARCHAR2(20 BYTE) NOT NULL,
    PRIMARY KEY(SCH_CODE)
);

DROP TABLE SCHOOL;
CREATE TABLE SCHOOL (
    SCH_CODE NUMBER(1) NOT NULL CONSTRAINT PK_SCHOOL PRIMARY KEY,
    SCH_NAME VARCHAR2(20 BYTE) NOT NULL   
);

DROP TABLE SCHOOL;
CREATE TABLE SCHOOL (
    SCH_CODE NUMBER(1) NOT NULL,
    SCH_NAME VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT PK_SCHOOL PRIMARY KEY(SCH_CODE)
);

-- 학생 테이블
-- 자식 테이블 : FK를 가진 테이블
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL PRIMARY KEY,
    SCH_CODE NUMBER(1) NOT NULL REFERENCES SCHOOL(SCH_CODE), -- 외래키 지정 스쿨테이블의 SCH_CODE
    STU_NAME VARCHAR2(20 BYTE) NULL
);

DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL ,
    SCH_CODE NUMBER(1) NOT NULL , -- 외래키 지정
    STU_NAME VARCHAR2(20 BYTE) NULL,
    PRIMARY KEY(STU_NO),
    FOREIGN KEY(SCH_CODE) REFERENCES SCHOOL(SCH_CODE)
);

DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL ,
    SCH_CODE NUMBER(1) NOT NULL , -- 외래키 지정
    STU_NAME VARCHAR2(20 BYTE) NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO),
    CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY(SCH_CODE) REFERENCES SCHOOL(SCH_CODE)
);

-- 최종 정리
--생성 : 부모먼저, 자식 나중
-- 삭제 : 자식먼저, 부모나중
DROP TABLE STUDENT;
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL(
   SCH_CODE NUMBER(1) NOT NULL,
    SCH_NAME VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT PK_SCHOOL PRIMARY KEY(SCH_CODE)   
);
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL ,
    SCH_CODE NUMBER(1) NOT NULL , -- 외래키 지정
    STU_NAME VARCHAR2(20 BYTE) NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO),
    CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY(SCH_CODE) REFERENCES SCHOOL(SCH_CODE)
);

--M:N관계 연습

DROP TABLE SIGN;
DROP TABLE STUDENT;
DROP TABLE SUBJECT;

CREATE TABLE STUDENT(
    STU_CODE CHAR(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2(20 BYTE) NOT NULL,
    STU_AGE NUMBER(2) NOT NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_CODE)   
);

CREATE TABLE SUBJECT (
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    SUB_NAME CHAR(4 BYTE) NOT NULL,
    SUB_PROFESSOR VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_CODE)
);

CREATE TABLE SIGN(
    SIGN_NO NUMBER(1) NOT NULL,
    STU_CODE CHAR(5 BYTE) NOT NULL,
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    CONSTRAINT PK_SIGN PRIMARY KEY(SIGN_NO),
    CONSTRAINT FK_SIGN_STUDNET FOREIGN KEY(STU_CODE) REFERENCES STUDENT(STU_CODE),
    CONSTRAINT FK_SIGN_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE)   
);



















