

DROP TABLE PROCEEDING;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;

DROP TABLE BONUS;
DROP TABLE DEPT;
DROP TABLE EMP;
DROP TABLE SALGRADE;
DROP TABLE USER_TBL;

CONN SYSTEM/1111;





DROP USER SCOTT;
--부서 테이블
CREATE TABLE DEPARTMENT(
    DEPT_NO VARCHAR2(15) NOT NULL,
    DEPT_NAME VARCHAR2(30),
    DEPT_LOCATION VARCHAR2(50)
    
);

--프로젝트 테이블
CREATE TABLE PROJECT(
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30),
    BEGIN_DATE DATE,
    END_DATE DATE
   
);

-- 사원 테이블 / 부서를 FK함
CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15),-- FK
    POSITION CHAR(10),
    NAME VARCHAR2(15),
    HIRE_DATE DATE,
    SALARY NUMBER
);

-- 프로젝트 진행 테이블 / 부서, 사원테이블 FK

CREATE TABLE PROCEEDING(
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER, --FK
    PJT_NO NUMBER, --FK
    PJT_STATE NUMBER NOT NULL
);

--기본키 추가
ALTER TABLE DEPARTMENT 
    ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO);
ALTER TABLE PROJECT
    ADD CONSTRAINT PK_PROJECT PRIMARY KEY(PJT_NO);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO);
ALTER TABLE PROCEEDING
    ADD CONSTRAINT PK_PROCEEDING PRIMARY KEY(PCD_NO);
    
--외래키 추가
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPT_NO)
        REFERENCES DEPARTMENT(DEPT_NO);

ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_EMPLOYEE FOREIGN KEY(EMP_NO)
        REFERENCES EMPLOYEE(EMP_NO);
        
ALTER TABLE PROCEEDING
    ADD CONSTRAINT FK_PROCEEDING_PROJECT FOREIGN KEY(PJT_NO)
        REFERENCES PROJECT(PJT_NO);

-- 외래키 제거
-- DEPARTMENT 테이블의 DEPT_NO 칼럼을 참조하는 외래키 제약조건을 제거해야
-- DEPARTMENT 테이블의 DEPT_NO 칼럼에 추가된 기본키 제약조건을 제거할 수 있다.
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT;

--    DROP FOREIGN KEY; 오라클에서 안됨 FK의 이름을 알아야한다

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEE'; -- EMPLOYEE의 제약조건 검색

-- 기본키 제거
-- FK에 의해서 참곶되고 있는 PK는 제거할 수 없음
-- 먼저 FK를 제거해야 함
ALTER TABLE DEPARTMENT
    DROP CONSTRAINT PK_DEPARTMENT; -- EMPLOYEE의 FK를 먼저 제거해야 실행할 수 있음
-- PRIMARY KEY의 이름을 모를때
ALTER TABLE DEPARTMENT
    DROP PRIMARY KEY;
    
ALTER TABLE PROCEEDING
    DROP CONSTRAINT PK_PROCEEDING;




    
    
