# server port
# web.xml
# session(1800 seconds = 30 minutes)

server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true  
    session: 
        timeout: 1800

# database connection      
spring:      
   datasource: 
     hikari:
       driver-class-name: oracle.jdbc.OracleDriver
       jdbc-url: oracle:thin:@localhost:1521:xe
       username: scott
       password: TIGER
    
# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml


